### ISSUE TITLE
Broadcast not received

### ISSUE THREAD

**Issue by tronku** [android/performance-samples#203]
I am currently using profileinstaller 1.3.0-alpha05 and benchmark 1.2.0-alpha08 in order to trigger baseline generator on A13 device without root. After upgrading the benchmark, I am not able to execute any macrobenchmark test and getting the below error

java.lang.IllegalStateException: The DROP_SHADER_CACHE broadcast was not received. This most likely means that the `androidx.profileinstaller` library used by the target apk is old. Please use `1.3.0-alpha02` or newer.

If i downgrade the benchmark to 1.1.1 and trigger the same macrobenchmark test then it's working fine.

**Comment by mlykotom** [comment]
Hey, pls re-check your dependencies.
The latest versions for
- profile installer version is 1.3.0-alpha02 
- benchmark is 1.2.0-alpha08

A bug slipped into the benchmark 1.2.0-alpha07 that cause the error message even if you've specified the proper profile installer version.

But it should be fixed in latest 1.2.0-alpha08

If you can't upgrade to 1.2.0-alpha08 you can temporarily add to your `:app` `AndroidManifest` this:
```
  <!-- workaround bug in profileinstaller 1.3.0-alpha02, remove when updating to alpha03+ -->
  <receiver
    android:name="androidx.profileinstaller.ProfileInstallReceiver"
    android:permission="android.permission.DUMP"
    android:exported="true">
    <intent-filter>
        <action android:name="androidx.profileinstaller.action.BENCHMARK_OPERATION" />
    </intent-filter>
  </receiver>
```

**Comment by oguzhanaslann** [comment]
@mlykotom  it did not work the issue in my case. Downgrade the benchmark to 1.1.1 worked though

**Comment by mlykotom** [comment]
The next version of profileinstaller was released, so once you update to [1.3.0-alpha03](https://developer.android.com/jetpack/androidx/releases/profileinstaller#1.3.0-alpha03), it should work.

**Comment by JCarlosR** [comment]
> @mlykotom it did not work the issue in my case. Downgrade the benchmark to 1.1.1 worked though
You mean downgrading this dependency in the benchmark module? `implementation 'androidx.benchmark:benchmark-macro-junit4:1.2.3'`

> The next version of profileinstaller was released, so once you update to [1.3.0-alpha03](https://developer.android.com/jetpack/androidx/releases/profileinstaller#1.3.0-alpha03), it should work.
Is this dependency needed for the macrobenchmark module or the app that is being tested?

**Comment by mehdiyari** [comment]
Hi @keyboardsurfer, I'm getting the same issue on the latest version of profile-installer(1.4.0), but only on a specific device (SUNMI L3 with Android 14). 

```
java.lang.IllegalStateException: The DROP_SHADER_CACHE broadcast was not received. This most likely means that the `androidx.profileinstaller` library used by the target apk is old. Please use `1.3.0-alpha02` or newer. For more information refer to the release notes at https://developer.android.com/jetpack/androidx/releases/profileinstaller. If you are already using 'androidx.profileinstaller' library and still seeing error, verify: 1) androidx.profileinstaller.ProfileInstallReceiver appears unobfuscated in your APK's AndroidManifest and dex, and 2) the following command executes successfully (should print 14}): adb shell am broadcast -a androidx.profileinstaller.action.BENCHMARK_OPERATION -e EXTRA_BENCHMARK_OPERATION DROP_SHADER_CACHE mypackage/androidx.profileinstaller.ProfileInstallReceiver
at androidx.benchmark.macro.MacrobenchmarkScope.dropShaderCache(MacrobenchmarkScope.kt:405)
at androidx.benchmark.macro.MacrobenchmarkKt.macrobenchmarkWithStartupMode$lambda$18(Macrobenchmark.kt:419)
at androidx.benchmark.macro.MacrobenchmarkKt.$r8$lambda$nYOYe9qoa3qEKOmAUA_HsQ_0qsY(Unknown Source:0)
at androidx.benchmark.macro.MacrobenchmarkKt$$ExternalSyntheticLambda3.invoke(D8$$SyntheticClass:0)
at androidx.benchmark.macro.MacrobenchmarkPhaseKt.runPhase(MacrobenchmarkPhase.kt:99)
at androidx.benchmark.macro.MacrobenchmarkKt.macrobenchmark$lambda$6(Macrobenchmark.kt:271)
at androidx.benchmark.macro.MacrobenchmarkKt.$r8$lambda$xwXnT_b4vi-hCaLpXAO_soLs9-w(Unknown Source:0)
at androidx.benchmark.macro.MacrobenchmarkKt$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
at androidx.benchmark.macro.TraceProcessorExtensionsKt.runServer(TraceProcessorExtensions.kt:163)
at androidx.benchmark.macro.TraceProcessorExtensionsKt.runServer$default(TraceProcessorExtensions.kt:158)
at androidx.benchmark.macro.MacrobenchmarkKt.macrobenchmark(Macrobenchmark.kt:263)
at androidx.benchmark.macro.MacrobenchmarkKt.macrobenchmarkWithStartupMode(Macrobenchmark.kt:400)
at androidx.benchmark.macro.junit4.MacrobenchmarkRule.measureRepeated(MacrobenchmarkRule.kt:87)
```

I checked, and the `adb shell am broadcast -a androidx.profileinstaller.action.BENCHMARK_OPERATION -e EXTRA_BENCHMARK_OPERATION DROP_SHADER_CACHE my-package/androidx.profileinstaller.ProfileInstallReceiver
` returns 14, but still have the issue on this device.

**Comment by appntech** [comment]
I have same issue on 1.4.1
